name: Test and Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.10', '3.12']  # Test minimum (3.10) and stable (3.12) versions
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install CMake (for espresso build)
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update
          sudo apt-get install -y cmake
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install cmake
        fi
      shell: bash
    
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    
    - name: Test import
      run: |
        python -c "from sboxanalyzer import *; print('Import * successful')"
        python -c "from sboxanalyzer import SboxAnalyzer; print('Import SboxAnalyzer successful')"
        python -c "import sboxanalyzer; print(f'Version: {sboxanalyzer.__version__}')"

  publish:
    name: Publish to PyPI
    needs: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for trusted publishing
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    
    - name: Build package
      run: python -m build
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
